spring:
  application:
    name: prana
  config:
    import: classpath:/env.yml
  datasource:
    url: jdbc:mysql://j12a103.p.ssafy.io:3316/prana
    username: ${PRANA_MYSQL_USER}
    password: ${PRANA_MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      #      hibernate.generate_statistics: true
      hibernate.log_slow_query: 1000
      hibernate.highlight_sql: true
      jakarta.persistence.schema-generation.database.action: none
      jakarta.persistence.schema-generation.scripts.action: none
      jakarta.persistence.create-database-schemas: false


  data:
    redis:
      host: prana-redis
      port: 6379



logging:
  level:
    com.prana: trace
    org.hibernate.SQL_SLOW: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

# AI 서버의 엔드포인트 URL 설정
ai:
  server:
    shortFeedbackUrl : http://ai-yoga:8000/api/short-feedback
    longFeedbackUrl : http://ai-yoga:8000/api/long-feedback