spring:
  application:
    name: prana
  config:
    import: classpath:/env.yml
  datasource:
    url: ${PRANA_MYSQL_URL}
    username: ${PRANA_MYSQL_USER}
    password: ${PRANA_MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      #      hibernate.generate_statistics: true
      hibernate.log_slow_query: 1000
      hibernate.highlight_sql: true
      jakarta.persistence.schema-generation.database.action: none
      jakarta.persistence.schema-generation.scripts.action: none
      jakarta.persistence.create-database-schemas: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: prana-yoplay

  data:
    redis:
      host: prana-redis
      port: 6379



logging:
  level:
    com.prana: info
    org.hibernate.SQL_SLOW: info
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info

# AI 서버의 엔드포인트 URL 설정
ai:
  server:
    shortFeedbackUrl : http://prana-ai:8000/api/short-feedback
    longFeedbackUrl : http://prana-ai:8000/api/long-feedback


# open AI
openai:
  api:
    key: ${OPENAI_API_KEY}